#!/usr/bin/env python3

import json

with open("experiments/valid_intervals", "r") as file:
    valid_intervals = json.load(file)

print()

for interval in valid_intervals.keys():
    print(interval, end=": ")
    print(valid_intervals[interval]["Start runNr"], end=" - ")
    if "End runNr" in valid_intervals[interval].keys():
        print(valid_intervals[interval]["End runNr"])
    else:
        print("Interrupted or ongoing")
print()

for interval in valid_intervals.keys():
    print(interval, end=": ")

    for key in valid_intervals[interval].keys():
        if key != "Start runNr" and key != "End runNr":
            print(key, end = " ")

    print()
print()

for interval in valid_intervals.keys():
    print(interval, end=": ")

    for key in valid_intervals[interval].keys():
        if key != "Start runNr" and key != "End runNr":
            print("Nr rounds:", len(valid_intervals[interval][key]))
            break
